import { version } from "react";

// src/services/endpoints.js
export const API_ENDPOINTS = {
  LOGIN: "auth/login",
  CREATE_USERS: "auth/create-user",
  GET_USERS: "auth/get-users",
  get_user_list:"auth/user-dropdown",
  update_emp_details: `auth/update-user`,
  get_jobRole_list: `get-jobRole`,
  change_password: `auth/set-password`,
  create_department: `department/create-department`,
  get_department: `department/get-deparments`,
  create_jobRole: `create-jobRole`,
  get_jobRole_list: `get-jobRole`,
  // upload_img: `upload-image`,
  upload_img: `upload-document`,
  get_user_docs: "get-documents",
  get_emp_details: `auth/get-employee-details`,
  update_emp_status: `/auth/user-status`,
  get_deleted_users: `/auth/get-deleted-users`,
  delete_users: `/auth/delete-user`,
  get_ip_requests: `auth/get-ip-requests`,
  approve_ip: `auth/approve-ip`,
  get_Emp_Attendance: `/attendance/daywise`,
  get_Emp_Attendance_Summary:  `attendance/monthly-summary`,
  get_Emp_Attendance_filter_search:`get-emp-attendance`,
  get_emp_visit_report:`get-emp-visit`,
  get_city:`get-districts`,
  upload_salary_slip:`upload-emp-salary`,
  get_attendance_images: `get-attendance-images`,
  get_daily_salary_report:`daily-salary-range`,
  get_emp_route: `get-route`,
  upload_emp_letters: `employee-letter`,
  get_emp_docs: `get-employee-documents`,
  document_status:`document-status`,
  send_esign: "documents/send-esign",
  digio_send_eSign: "letters/send-esign",
  verify_pan: "/verify-pan",
  verify_mobile_no:"/digilocker-kyc",
  // get_aadhar_pan_kid:`/kyc-status/response`,
  get_aadhar_pan_kid: (kycId) => `/kyc-status/${kycId}/response`,
  check_digio_Status: `letters/document-status`,
  download_Signed_Letter_digio: `download-signed-pdf`,
  Gst_verify:`verify-gst`,
  set_expense_allocation:`set-expense-allocation`,
  get_uploaded_exp: `admin-expense-summary`,
  emp_daily_summary: `daily-summary`,
  get_distributors:  `get-distributorsList`,
  distributor_onbording_form:`/create-distributor`,
  update_distributor: `update-distributor`,
  get_distributor: `get-distributor`,
  delete_distributor: `delete-distributor`,
  uplaod_distributor_agreement_pdf: `/upload-agreement`,
  get_distributor_agreement_pdf:`get-distributor-agreement`,
  get_distributor_send_esign:`distributor/send-esign`,
  get_distributor_esign_status:`/distributor/status`,
  download_distributor_signed_agreement:`distributor/download`,
   create_company:`company/create-company`,
};
// 