import { version } from "react";

// src/services/endpoints.js
export const API_ENDPOINTS = {
  LOGIN: "auth/login",
  CREATE_USERS: "auth/create-user",
  GET_USERS: "auth/get-users",
  get_user_list:"auth/user-dropdown",
  update_emp_details: `auth/update-user`,
  get_jobRole_list: `get-jobRole`,
  change_password: `auth/set-password`,
  create_department: `department/create-department`,
  get_department: `department/get-deparments`,
  create_jobRole: `create-jobRole`,
  get_jobRole_list: `get-jobRole`,
  // upload_img: `upload-image`,
   update_profile_image: `/auth/upload-profile-image`,
  auth_my_profile:  `/auth/my-profile`,
  upload_img: `upload-document`,
  // notifiction 
  Get_notification:`auth/get-notifications`,
  Mark_single_notificaction:`auth/mark-notification-as-read`,
  Mark_all_asread_notifiction:`auth/mark-allAsRead`,
  Delete_all_notifiction:`auth/deleteAllNotifications`,
  Delete_single_one_notification:`auth/delete-notification`,
  // get user/emp
  get_user_docs: "get-documents",
  get_emp_details: `auth/get-employee-details`,
  update_emp_status: `/auth/user-status`,
  get_deleted_users: `/auth/get-deleted-users`,
  delete_users: `/auth/delete-user`,
  get_ip_requests: `auth/get-ip-requests`,
  approve_ip: `auth/approve-ip`,
  get_Emp_Attendance: `/attendance/daywise`,
  get_Emp_Attendance_Summary:  `attendance/monthly-summary`,
  get_Emp_Attendance_filter_search:`get-emp-attendance`,
  get_emp_visit_report:`get-emp-visit`,
  get_city:`get-districts`,
  upload_salary_slip:`upload-emp-salary`,
  get_attendance_images: `get-attendance-images`,
  get_daily_salary_report:`daily-salary-range`,
  get_emp_route: `get-route`,
  upload_emp_letters: `employee-letter`,
  get_emp_docs: `get-employee-documents`,
  document_status:`document-status`,
  send_esign: "documents/send-esign",
  digio_send_eSign: "letters/send-esign",
  verify_pan: "/verify-pan",
  verify_mobile_no:"/digilocker-kyc",
  // get_aadhar_pan_kid:`/kyc-status/response`,
  get_aadhar_pan_kid: (kycId) => `/kyc-status/${kycId}/response`,
  check_digio_Status: `letters/document-status`,
  download_Signed_Letter_digio: `download-signed-pdf`,
  Gst_verify:`verify-gst`,
  set_expense_allocation:`set-expense-allocation`,
  get_uploaded_exp: `admin-expense-summary`,
  emp_daily_summary: `daily-summary`,
  get_distributors:  `get-distributorsList`,
  distributor_onbording_form:`/create-distributor`,
  update_distributor: `update-distributor`,
  get_distributor: `get-distributor`,
  delete_distributor: `delete-distributor`,
  uplaod_distributor_agreement_pdf: `/upload-agreement`,
  get_distributor_agreement_pdf:`get-distributor-agreement`,
  get_distributor_send_esign:`distributor/send-esign`,
  get_distributor_esign_status:`/distributor/status`,
  download_distributor_signed_agreement:`distributor/download`,
   create_company:`create-company`,
   Get_comapnies:`get-companies`,
   Get_comapany_by_id:`get-company`,
   Update_comapany:`update-company`,
   Delete_company:`delete-company`,
  //  stock group
  create_stock_group:`create-stockGroup`,
  stock_group_list:`get-stockGroup`,
  Get_stock_group_by_id:`get-stockGroup`,
  Update_stock_group:`update-stockGroup`,
  Delete_stock_group:`delete-stockGroup`,
  get_categories_by_stock_group: 'get-categories-by-stock-group',

  // stock category
  Create_stock_category:`create-stock-category`,
  View_stock_category:`get-stock-categories`,
  View_stock_category_by_id:`/get-stock-category`,
  Update_stock_category_by_id:`update-stock-category`,
  Delete_Stock_category_by_id:`delete-stock-category`,

  //set-team-target
  create_team: `create-team`,
  create_sub_team: `create-subteam`,
  get_subTeam_by_team: 'get-subteams',
  get_team_list: `get-teams`,
  get_team_by_id: `getTeam`,
  get_users_by_role: `users-by-level`,
  assign_target: 'assign-target',
  get_assigned_targets: 'get-assigned-targets',
  get_assigned_targets_by_id: "get-assigned-target",
  edit_assigned_targets: "edit-assigned-target",
  delete_assigned_targets: "delete-assigned-target",

  assign_individual_targets: 'assign-employee-target',
  get_individual_targets: 'get-employee-targets',
  get_individual_targets_by_id: 'get-employee-targets-by-id',
  edit_individual_target: 'update-employee-targets',
  delete_individual_target: 'delete-employee-targets',

  get_team_by_id: 'getTeam',
  edit_team: 'update-team',
  delete_team: "delete-team",
  edit_suTeam: "update-subteam",
  delete_subTeam: "delete-subteam",
  create_godown: "create-godown",
  godown_list: "getGodownList",
  view_godown_by_id: "getGodownDetails",
  update_godown: "update-godown",
  delete_godown: "delete-godown",
  get_unique_quantity_codes: "get-unitOfMeasure-list",
  create_unit_of_measure: "create-unitOfMeasure",
  getUnitList: "getAllUnits",
  getSimpleUnitList: "get-simple-units",
  get_unit_by_id: "getUnitById",
  edit_unitOfMeasure: "editUnitOfMeasure",
  delete_unitOfMeasure: "deleteUnit",

  create_stock_item: "create-stock-item",
  getStockItemsList: "get-stock-items",
  getStockItemById: "getstockItemByID",
  updateStockItem: "update-stock-item",
  deleteStockItem: "delete-stock-item",

  create_account_group: "create-accounting-group",
  get_account_group_list: "account-group-list",
  get_account_by_id: "account-group-details",
  edit_account_group: "update-account-group",
  delete_account_group: "delete-account-group",

  create_ledger: "create-ledger",
  get_ledger: "get-ledgers",
  get_ledger_by_id: "getLedgerDetailsById",
  update_ledger: "update_ledger",
  delete_ledger: "delete_ledger"
};
// 