// src/utils/ledgerGroupConfig.js

export const GROUP_CONFIG = {
  "Bank Account": {
    showInterest: true,
    showBankDetails: true,
    showTax: true,
    showBankConfig: true,
    showInventory: false,
    showPan: false,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "stock in hand": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: false,
    showPan: false,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Suspense account": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: false,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Bank occ a/c": {
    showInterest: true,
    showBankDetails: true,
    showTax: true,
    showBankConfig: true,
    showInventory: false,
    showPan: false,
    showOdLimit: true,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Bank od a/c": {
    showInterest: true,
    showBankDetails: true,
    showTax: true,
    showBankConfig: true,
    showInventory: false,
    showPan: false,
    showOdLimit: true,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Cash in hand": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: false,
    showPan: false,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Branch/Division": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: true,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Capital account": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: true,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Deposit(assets)": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  Investment: {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Misc. expense(assets)": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Reserves & surplus": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Retained earning": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Current assets": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: true,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Current liabilities": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: true,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Loans & advances(assets)": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: true,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Loans(liabilities)": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  Provision: {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: true,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Unsecured Loans": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Secured loans": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,
    showBillByBill: false,
    showCreditLimit: false,
    showCreditPeriod: false,
    showVoucherCheck: false,
  },

  "Sundry creditors": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,

    showBillByBill: true,
    showCreditLimit: true,
    showCreditPeriod: true,
    showVoucherCheck: true,
  },

  "Sundry debtors": {
    showInterest: true,
    showBankDetails: false,
    showTax: true,
    showBankConfig: false,
    showInventory: true,
    showPan: true,
    showOdLimit: false,
    showPayroll: false,

    showBillByBill: true,
    showCreditLimit: true,
    showCreditPeriod: true,
    showVoucherCheck: true,
  },
};

export const DEFAULT_GROUP_CONFIG = {
  showInterest: false,
  showBankDetails: false,
  showTax: false,
  showBankConfig: false,
  showInventory: false,
  showPan: false,
  showOdLimit: false,
  showPayroll: false,
  showBillByBill: false,
  showCreditLimit: false,
  showCreditPeriod: false,
  showVoucherCheck: false,
};