// Extracts the phrase that follows a keyword in a message string.
// e.g. extractAfterKeyword("Sales request generated by Dinesh", "generated by") -> "Dinesh"
export const extractAfterKeyword = (message = "", keyword = "") => {
  if (!message) return "";
  const idx = message.toLowerCase().indexOf(keyword.toLowerCase());
  if (idx === -1) return "";
  return message
    .slice(idx + keyword.length)
    .trim()
    .replace(/[.\s]+$/, ""); // strip trailing period/whitespace only
};

// SO-{userId}-{approvalId}
export const buildSalesOrderNumber = (userId, id) =>
  `EMP-${userId}-${id}`;

// "2026-06-20T10:53:38.000Z" -> "20-06-2026"
export const formatDate = (dateString) => {
  if (!dateString) return "";
  const date = new Date(dateString);
  if (Number.isNaN(date.getTime())) return "";
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  return `${day}-${month}-${year}`;
};

export const STATUS_COLORS = {
  PENDING: "orange",
  APPROVED: "green",
  REJECTED: "red",
  CANCELLED: "gray",
};

export const getStatusColor = (status) =>
  STATUS_COLORS[(status || "").toUpperCase()] || "gray";